### ISSUE TITLE
client.bars(symbol, frequency, start, offset)中参数start如何填写？

### ISSUE THREAD

**Issue by starsun7** [mootdx/mootdx#12]
start参数说明是起始位置，起始位置是什么意思，我测试输入‘2022-02-02’，不对；
输入整数，是可以，但是0，1，2等整数代表什么意思？
谢谢

**Comment by bopo** [comment]
请参阅手册

**Comment by bopo** [comment]
一次start 是0，表示从0开始，
第二次 start 是 offset 的只，表示从第一次结束位置向后获取
