### ISSUE TITLE
bar的最大获取值是2000条， 2000条以前的历史数据哪里可以获得？

### ISSUE THREAD

**Issue by ykk648** [mootdx/mootdx#21]

**Comment by bopo** [comment]
这个看股票代码了，有的股票多，有的股票少，一版每次800，可以进行分页获取

client.bars(symbol='600036', start=900, offset=800)

start 是起始位置， offset 为每次多少条，最大800，如果是800，那么start 就是800的倍数

例如 第一次0。第二次800，第三次 1600...一次类推

**Comment by ykk648** [comment]
目前用掘金或者tdx手动离线的分钟数据 thx
