### ISSUE TITLE
用Quotes.bars读ETF基金的数据失败

### ISSUE THREAD

**Issue by thinkingLiuf** [mootdx/mootdx#25]
![image](https://user-images.githubusercontent.com/117700443/202137265-110a452b-ba57-4c5a-99c0-6036c03b056e.png)
![image](https://user-images.githubusercontent.com/117700443/202137466-ce722d2e-07b7-4502-ba2f-4f7176843e75.png)

**Comment by bopo** [comment]
请更新最新版本 v0.9.5

**Comment by bopo** [comment]
新版已经解决

**Comment by dgg2023** [comment]
哈，我用pytdx也出现过类似错误提示。后来查到的原因是重连太多。（500个开始抛错误）
