### ISSUE TITLE
读不了通达信本地存储的期货和期权数据

### ISSUE THREAD

**Issue by xiaoxinccr** [mootdx/mootdx#33]
reader = Reader.factory(market='ext', tdxdir='C:\\new_jyplug')
print(reader.daily(symbol='74#TFIV.day'))
返架结果为none

**Comment by bopo** [comment]
感谢提交问题，我会复查

**Comment by bopo** [comment]
不要加.day

**Comment by xiaoxinccr** [comment]
谢谢支持！

bopo.wang ***@***.***>于2023年4月14日 周五09:43写道：
