### ISSUE TITLE
【BUG】 incon.dat所处的位置是在TDX的根目录，修改如下图：

### ISSUE THREAD

**Issue by MeditatorV** [mootdx/mootdx#35]
资料参数：https://blog.csdn.net/liuyukuan/article/details/79483812
修改parse.py文件：

![image](https://user-images.githubusercontent.com/47035563/231438294-eced569a-a25d-464f-becc-fd26e94f78c8.png)

![image](https://user-images.githubusercontent.com/47035563/231441614-d26f1751-1972-437a-a1c3-a4d8b63fb402.png)

**Comment by bopo** [comment]
这应该是新版本路径，之后会修正

**Comment by bopo** [comment]
新版已经修复
