### ISSUE TITLE
多线程调用时候采用bestip=True出现异常

### ISSUE THREAD

**Issue by bthuntergg** [mootdx/mootdx#44]
2023-06-29 01:27:19,419 - mootdx - INFO - [-] 选择最快的服务器...
21775
连接服务器tdx[1]异常:Set of coroutines/Futures is empty.,11111111111
连接服务器tdx[2]异常:Set of coroutines/Futures is empty.,11111111111

**Comment by bopo** [comment]
经测试，确实是个bug，加入修复任务，下版本会修复
