### ISSUE TITLE
请问numpy和pandas这些依赖能否不指定版本？

### ISSUE THREAD

**Issue by allran** [mootdx/mootdx#54]

**Comment by bopo** [comment]
pandas 1.5+

**Comment by markcheney1** [comment]
> pandas 1.5+

是否可以修改requirments.txt文件，将numpy==1.24.3 ; pandas==1.5.3改成numpy>=1.24.3 ; pandas>=1.5.3，如果限定了pandas和numpy帮忙，在解决本地依赖会有点问题

**Comment by bopo** [comment]
> > pandas 1.5+
> 
> 题主估计是这个意思：修改pyproject.toml文件，将pandas = "^1.5.2" 改成pandas=">=1.5.2"，如果限定了pandas版本，在解决本地依赖，包管理的时候，本地环境也会被限制在固定的版本。 @bopo 

并不需要修改本身就是1.5.2+

**Comment by bopo** [comment]
这个之后考虑一下版本问题，可能会降低版本需求，更具兼容性

**Comment by markcheney1** [comment]
> > > pandas 1.5+
> > 
> > 
> > 题主估计是这个意思：修改pyproject.toml文件，将pandas = "^1.5.2" 改成pandas=">=1.5.2"，如果限定了pandas版本，在解决本地依赖，包管理的时候，本地环境也会被限制在固定的版本。 @bopo
> 
> 并不需要修改本身就是1.5.2+
支持1.5.2+，这个不准确，^1.5.2约束范围是>=1.5.2  <2.0.0，现在pandas新版本已经是2.1.1，https://pandas.pydata.org/docs/whatsnew/v2.1.1.html

**Comment by bopo** [comment]
已经解决
