### ISSUE TITLE
可以读取tick数据和集合竞价数据吗？

### ISSUE THREAD

**Issue by MeditatorV** [mootdx/mootdx#61]
查看了文档暂时没有发现读取tick数据和集合竞价数据的方法，特来此咨询，望告知，感谢

**Comment by MeditatorV** [comment]
位于以下可查询到分笔成交数据
https://www.mootdx.com/zh_CN/latest/api/quote1/
08. 查询分笔成交
09. 查询历史分笔

**Comment by 279632990** [comment]
> 位于以下可查询到分笔成交数据 https://www.mootdx.com/zh_CN/latest/api/quote1/ 08. 查询分笔成交 09. 查询历史分笔

实时分笔接口数据错误，要么查询为空，要么就是价格是未知股票的
