### ISSUE TITLE
Affair.parse报错，字段更名似乎出现不匹配BUG

### ISSUE THREAD

**Issue by davidqing2000** [mootdx/mootdx#64]
代码：
from mootdx.affair import Affair

Affair.fetch(downdir='output', filename='gpcw20170930.zip')

data = Affair.parse(downdir='output', filename='gpcw20170930.zip')

报错：
Exception has occurred: ValueError
Length mismatch: Expected axis has 582 elements, new values have 581 elements
    data = Affair.parse(downdir='output', filename='gpcw20170930.zip')
ValueError: Length mismatch: Expected axis has 582 elements, new values have 581 elements

**Comment by davidqing2000** [comment]
新版本V0.11.1匹配问题已解决，但是 col581没有列名文字说明

**Comment by bopo** [comment]
现已经修复

**Comment by bopo** [comment]
现已经修复
