### ISSUE TITLE
获取除权信息失败

### ISSUE THREAD

**Issue by liuts** [mootdx/mootdx#7]
可以正常获取数据，但是继续获取除权数据时候，显示连接超时。请测试确认是不是有问题

from mootdx.quotes import Quotes

client = Quotes.factory(market='std')
print(client)
data1=client.bars(symbol='600521', frequency=9, offset=10)
print(data1)

# 前复权
data = client.bars(symbol='600521', adjust='qfq')
print(data)

**Comment by bopo** [comment]
正调整中,,, 请关注最新版本

**Comment by bopo** [comment]
这不是除权信息失败，是复权数据

**Comment by wenxingxing** [comment]
文档有问题，前复权要自己算的。

**Comment by bopo** [comment]
我尝试下，如果可以，就用你的代码

**Comment by bopo** [comment]
新版本已经修复
