### ISSUE TITLE
should we return pd.DataFrame(None)?

### ISSUE THREAD

**Issue by rouniuyizu** [mootdx/mootdx#91]
https://github.com/mootdx/mootdx/blob/98d87a655c2669dd0f02bf0c328ab35c6641cf4d/mootdx/utils/factor.py#L28

从调用者的调度来看，如果是empty的话就认为没有相关信息或许也是一种方式
https://github.com/mootdx/mootdx/blob/98d87a655c2669dd0f02bf0c328ab35c6641cf4d/mootdx/tools/reversion.py#L13

**Comment by bopo** [comment]
好的，感谢反馈
